id: 0
width: 640
height: 480
dist:
  - - -0.150044
    - 0.051017
    - 0.000000
    - 0.000000
    - -0.067817
mtx:
  - - 180.971415
    - 0.000000
    - 148.729196
  - - 0.000000
    - 180.598787
    - 121.966872
  - - 0.000000
    - 0.000000
    - 1.000000
filter_on: False
filter_frame: 5
marker_size: 0.012
marker2global:
  translation:
    - - 0.0
      - 0.0
      - -25.0
  rotation:
    - - - 1.0
        - 0.0
        - 0.0
      - - 0.0
        - -1.0
        - 0.0
      - - 0.0
        - 0.0
        - -1.0