id: 0
dist:
  - - -0.150044
    - 0.051017
    - 0.000000
    - 0.000000
    - -0.067817
mtx:
  - - 180.971415
    - 0.000000
    - 148.729196
  - - 0.000000
    - 180.598787
    - 121.966872
  - - 0.000000
    - 0.000000
    - 1.000000