id: 0
width: 640
height: 480
dist:
  - - 0.013935
    - -0.024888
    - 0.000000
    - 0.000000
    - -0.033104
mtx:
  - - 331.235743
    - 0.000000
    - 322.030466
  - - 0.000000
    - 331.562160
    - 250.475216
  - - 0.000000
    - 0.000000
    - 1.000000