adaptiveThreshConstant: 7
adaptiveThreshWinSizeMin: 3
adaptiveThreshWinSizeMax: 23
adaptiveThreshWinSizeStep: 5
minMarkerPerimeterRate: 0.05
maxMarkerPerimeterRate: 3.0
polygonalApproxAccuracyRate: 0.01
minCornerDistanceRate: 0.05
minDistanceToBorder: 1
minMarkerDistanceRate: 0.05
markerBorderBits: 1
perspectiveRemovePixelPerCell: 8
perspectiveRemoveIgnoredMarginPerCell: 0.13
maxErroneousBitsInBorderRate: 0.04
minOtsuStdDev: 5.0
cornerRefinementMethod: 2
cornerRefinementWinSize: 5
cornerRefinementMaxIterations: 50
cornerRefinementMinAccuracy: 0.001
errorCorrectionRate: 0.1
useAruco3Detection: 1
minSideLengthCanonicalImg: 16
minMarkerLengthRatioOriginalImg: 0.05